- name: Remove Node.js
  become: yes
  yum:
    name: nodejs
    state: absent

- name: Install npm v10
  become: yes
  yum:
    name: https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodejs-10.9.0-1nodesource.x86_64.rpm

- name: Install optional
  become: yes
  yum:
    name:
    - gcc-c++
    - make

- name: Install vue-cli
  become: yes
  npm:
    name: "vue-cli"
    global: true

- name: Install bootstrap
  become: yes
  npm:
    name: "{{ item }}"
    state: 
  with_items:
    - bootstrap
    - bootstrap-vue
    - @fortawesome/fontawesome-svg-core
    - @fortawesome/free-solid-svg-icons
    - @fortawesome/vue-fontawesome
    - axios
    - vuex
    - vee-validate@2.2.15