- name: Remove Node.js
  become: yes
  yum:
    name: nodejs
    state: absent

- name: Install npm v10
  become: yes
  yum:
    name: https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodejs-10.9.0-1nodesource.x86_64.rpm

- name: Install optional
  become: yes
  yum:
    name:
    - gcc-c++
    - make

- name: Install vue-cli
  become: yes
  npm:
    name: "vue-cli"
    global: true

    
# - name: pull from git
#   become: yes
#   git:
#     repo: https://github.com/ju0731/automation.git
#     dest: /

- name: install webpack
  become: yes
  shell: | 
    npm init -y

    npm install -g webpack --save-dev

    npm install -g webpack-cli

    npm install -g -D
  # args:
  #   chdir: /home/ec2-user/automation/